#!/usr/bin/env bash
# init.sh — one-time Supabase setup
#
# Run this once from the server:
#   bash ~/stacks/supabase/init.sh
#
# What it does:
#   1. Clones the official Supabase docker files into ~/stacks/supabase/
#   2. Generates all required secrets
#   3. Creates a ready-to-fill .env file

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
ok()      { echo -e "  ${GREEN}✓${NC}  $*"; }
info()    { echo -e "  ${BLUE}→${NC}  $*"; }
warn()    { echo -e "  ${YELLOW}⚠${NC}  $*"; }
section() { echo; echo -e "${BOLD}$*${NC}"; echo "────────────────────────────────────────"; }

SUPABASE_DIR="${HOME}/stacks/supabase"

section "Supabase — initial setup"

# ── 1. Clone official docker files ───────────────────────────────────────────
if [[ -d "${SUPABASE_DIR}/volumes" ]]; then
  ok "Supabase docker files already present"
else
  info "Cloning Supabase docker files..."
  git clone --depth 1 --filter=blob:none --sparse \
    https://github.com/supabase/supabase.git /tmp/supabase-clone
  cd /tmp/supabase-clone
  git sparse-checkout set docker
  cp -r docker/volumes "${SUPABASE_DIR}/"
  cp docker/docker-compose.yml "${SUPABASE_DIR}/docker-compose.supabase.yml"
  rm -rf /tmp/supabase-clone
  ok "Docker files cloned"
fi

# ── 2. Generate secrets ───────────────────────────────────────────────────────
section "Generating secrets"

JWT_SECRET=$(openssl rand -base64 40 | tr -d '\n/+=' | head -c 40)

# Generate ANON_KEY and SERVICE_ROLE_KEY as proper JWTs using Node in Docker
info "Generating JWT tokens..."
TOKENS=$(docker run --rm -e JWT_SECRET="${JWT_SECRET}" node:alpine node -e '
const secret = process.env.JWT_SECRET;
const now = Math.floor(Date.now() / 1000);
const exp = now + (5 * 365 * 24 * 60 * 60); // 5 years

function base64url(obj) {
  return Buffer.from(JSON.stringify(obj)).toString("base64url");
}

function sign(payload) {
  const crypto = require("crypto");
  const header = base64url({ alg: "HS256", typ: "JWT" });
  const body = base64url(payload);
  const sig = crypto.createHmac("sha256", secret)
    .update(header + "." + body).digest("base64url");
  return header + "." + body + "." + sig;
}

const anon = sign({ role: "anon", iss: "supabase", iat: now, exp });
const service = sign({ role: "service_role", iss: "supabase", iat: now, exp });
console.log(anon + "|" + service);
')

ANON_KEY=$(echo "$TOKENS" | cut -d'|' -f1)
SERVICE_ROLE_KEY=$(echo "$TOKENS" | cut -d'|' -f2)
SECRET_KEY_BASE=$(openssl rand -hex 32)
REALTIME_DB_ENC_KEY=$(openssl rand -hex 8)   # 16 chars
VAULT_ENC_KEY=$(openssl rand -hex 16)          # 32 chars
PG_META_CRYPTO_KEY=$(openssl rand -hex 16)     # 32 chars
POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '\n/+=')
DASHBOARD_PASSWORD=$(openssl rand -base64 16 | tr -d '\n/+=')
S3_KEY_ID=$(openssl rand -hex 8)
S3_KEY_SECRET=$(openssl rand -hex 20)
POOLER_TENANT_ID="oryx-supabase"

ok "Secrets generated"

# ── 3. Write .env ─────────────────────────────────────────────────────────────
section "Writing .env"

ENV_FILE="${SUPABASE_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  warn ".env already exists — skipping (delete it to regenerate)"
else
  cat > "${ENV_FILE}" << EOF
############################################################
# Supabase — generated by init.sh
# KEEP THIS FILE SECRET — never commit it
############################################################

# ── Postgres ─────────────────────────────────────────────
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── JWT / API keys ────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_SECRET_KEY=${SERVICE_ROLE_KEY}

# ── Public URL (update with your actual domain) ───────────
SUPABASE_PUBLIC_URL=https://supabase.aritra.fyi
API_EXTERNAL_URL=https://supabase.aritra.fyi
SITE_URL=https://supabase.aritra.fyi

# ── Studio dashboard ──────────────────────────────────────
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
STUDIO_DEFAULT_ORGANIZATION=oryx
STUDIO_DEFAULT_PROJECT=default

# ── Auth ──────────────────────────────────────────────────
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false
ENABLE_ANONYMOUS_USERS=false
JWT_EXPIRY=3600
ADDITIONAL_REDIRECT_URLS=
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

# ── SMTP (optional — for auth emails) ────────────────────
SMTP_ADMIN_EMAIL=admin@aritra.fyi
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=oryx

# ── Storage ───────────────────────────────────────────────
GLOBAL_S3_BUCKET=supabase-storage
STORAGE_TENANT_ID=oryx
REGION=local
IMGPROXY_AUTO_WEBP=true
S3_PROTOCOL_ACCESS_KEY_ID=${S3_KEY_ID}
S3_PROTOCOL_ACCESS_KEY_SECRET=${S3_KEY_SECRET}

# ── Realtime ─────────────────────────────────────────────
SECRET_KEY_BASE=${SECRET_KEY_BASE}
REALTIME_DB_ENC_KEY=${REALTIME_DB_ENC_KEY}
VAULT_ENC_KEY=${VAULT_ENC_KEY}

# ── Pooler ────────────────────────────────────────────────
POOLER_TENANT_ID=${POOLER_TENANT_ID}
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_DB_POOL_SIZE=5
KONG_HTTP_PORT=8000

# ── Misc ─────────────────────────────────────────────────
PGRST_DB_SCHEMAS=public,storage,graphql_public
PGRST_DB_MAX_ROWS=
PGRST_DB_EXTRA_SEARCH_PATH=public
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}
FUNCTIONS_VERIFY_JWT=false
OPENAI_API_KEY=
EOF
  ok ".env written to ${ENV_FILE}"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
section "Setup complete"
echo
echo -e "  ${BOLD}Dashboard password: ${DASHBOARD_PASSWORD}${NC}"
echo -e "  ${BOLD}Postgres password:  ${POSTGRES_PASSWORD}${NC}"
echo
warn "Save these credentials in Bitwarden NOW before proceeding"
echo
echo "  Next steps:"
echo "  1. Store credentials in Bitwarden"
echo "  2. cd ~/stacks/supabase"
echo "  3. docker compose -f docker-compose.supabase.yml up -d"
echo "  4. Access Studio at http://192.168.2.100:8000"
echo
